using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Verse;

namespace DArcaneTechnology
{
    public static class GearAssigner
    {
        public static HashSet<string> exemptProjects = new HashSet<string>
        {
            "ComplexClothing",
            "ROM_OccupationClothing",
            "HighClassClothing",
            "RatkinClothing",
            "VAE_CasualWear",
            "VAE_FormalWear",
            "VAE_WorkAttire",
            "VAE_SterileAttire",
            "VAE_MilitaryClothing",
            "ApparelloTribalwearDesign",
            "ApparelloResearchDesign",
            "ApparelloResearchWork",
            "ApparelloResearchSF",
            "ApparelloResearchQuilting"
        };

        public static Dictionary<string, string> overrideAssignment = new Dictionary<string, string>
        {
           
        };


        public static Dictionary<string, string> hardAssignment = new Dictionary<string, string>
        {
            // Core & some CE
            {"Gun_Minigun", "GasOperation"},
            {"Apparel_PsychicFoilHelmet", "PTPsychicWorkbench"},
            {"Weapon_GrenadeFrag", "Machining"},
            {"Weapon_GrenadeMolotov", "Machining"},
            {"Weapon_GrenadeSmoke", "Machining"},
            {"Gun_TripleRocket", "AdvancedFabrication"},
            {"Gun_DoomsdayRocket", "AdvancedFabrication"},
            {"Gun_Needle", "AdvancedFabrication"},
            {"CE_Gun_M72LAW", "CE_AdvancedLaunchers"},
            {"CE_Melee_WraithBlade", "AdvancedFabrication"},
            {"Gun_ChargeBlasterHeavy", "ChargedShot"},
            {"Gun_InfernoCannon", "ChargedShot"},
            {"Gun_ChargeLance", "ChargedShot"},
            {"OrbitalTargeterBombardment", "MicroelectronicsBasics"},
            {"OrbitalTargeterPowerBeam", "MicroelectronicsBasics"},
            {"TornadoGenerator", "MicroelectronicsBasics"},
            {"Apparel_PsyfocusHelmet", "RoyalApparel"},
            {"Apparel_PsyfocusShirt", "RoyalApparel"},
            {"Apparel_PsyfocusVest", "RoyalApparel"},
            {"Apparel_PsyfocusRobe", "RoyalApparel"},
            {"MeleeWeapon_MonoSwordBladelink", "AdvancedFabrication"},
            {"MeleeWeapon_ZeusHammerBladelink", "AdvancedFabrication"},
            {"MeleeWeapon_PlasmaSwordBladelink", "AdvancedFabrication"},
            {"MeleeWeapon_MonoSword", "AdvancedFabrication"},
            {"MeleeWeapon_Zeushammer", "AdvancedFabrication"},
            {"MeleeWeapon_PlasmaSword", "AdvancedFabrication"},
            {"OrbitalTargeterMechCluster", "AdvancedFabrication"},
            {"MeleeWeapon_PsyfocusStaff", "AdvancedFabrication"},
            {"Weapon_GrenadeFlashbang", "CE_Launchers"},
            {"Weapon_GrenadeStickBomb", "CE_Launchers"},
            {"Weapon_GrenadeFirefoam", "CE_Launchers"},
            {"CE_ExplosiveBoltProjector", "ChargedShot"},
            {"AA_Flamethrower", "GasOperation"},
            {"OrbitalTargeterMechFall", "MicroelectronicsBasics"},
            // Android Tiers
            {"Mech40MMCannon", "ATPP_ResearchSM7"},
            {"MechMastiffGun", "ATPP_ResearchSM7"},
            {"MechHandCannon", "ATPP_ResearchSM7"},
            // Astra Imperium
            {"MeleeWeapon_MechKnife", "ATPP_ResearchSM7"},
            {"IG_ARM_StdChaosMarineA", "ARSAstarteArmor"},
            {"IG_ARM_StdChaosMarineB", "ARSAstarteArmor"},
            {"IG_HELM_StdChaosMarineA", "ARSAstarteArmor"},
            {"IG_ChaosVoidShieldBelt", "ARSAstarteArmor"},
            {"IG_Melee_ChaosChainsword", "ART3Augments"},
            {"IG_Melee_ChaosPowerAxe", "ART3Augments"},
            {"IG_Gun_CMBoltGun", "IG_RES_T2BoltGun"},
            {"IG_Gun_CMPlasmaRifle", "WRPlasmaRifle"},
            {"IG_Gun_DreadRktLauncher", "WRQuadRktLauncher"},
            {"TG_StdArmor", "ARStdImpArmor"},
            {"TG_StdHelmet", "ARStdImpArmor"},
            {"TG_FlakPlate", "ARFlakPlates"},
            {"TGGrenade_Krak", "WRKrakGrenade"},
            {"Gun_TGLasPistol", "WRLasPistol"},
            {"Gun_TGLasGun", "WRLasGun"},
            {"Gun_TGBoltGun", "WRBoltGun"},
            {"Gun_TGExitusSniper", "WRExitusSniper"},
            {"Gun_TGPlasmaRifle", "WRPlasmaRifle"},
            {"Gun_TGQuadRktLauncher", "WRQuadRktLauncher"},
            {"Gun_TGImpGrenadeLauncher", "WRGrenadeLauncher"},
            {"ROM_Gun_PumpShotgun_COC", "Gunsmithing"},
            {"ROM_Gun_SurvivalRifle_COC", "Gunsmithing"},
            {"ROM_Gun_LPRifle_COC", "Gunsmithing"},
            {"Apparel_CrystalShieldBelt", "CrystalloidProduction"},
            // Psitech
            {"Gun_CrystalZapper", "PsionicWeapons"},
            {"AnnihilationStaff", "PsionicWeapons"},
            // Glittertech
            {"Apparel_HC1Shield", "ElectroPlasmatics"},
            {"Apparel_OCShield", "ElectroPlasmatics"},
            {"Apparel_NanoSuit", "DynElect"},
            {"Apparel_NanoSuitHelmet", "DynElect"},
            {"Apparel_Reactive", "DynElect"},
            {"Apparel_NanoSkin", "DynElect"},
            {"Apparel_NanoSpeed", "DynElect"},
            {"Apparel_OCCombatVest", "ElectroPlasmatics"},
            {"Apparel_OCHelmet", "ElectroPlasmatics"},
            {"Gun_APB-1Pistol", "DynElect"},
            {"Gun_APB-1Projector", "DynElect"},
            {"Gun_APB-1Rifle", "DynElect"},
            {"Gun_EMRifle", "DynElect"},
            {"Gun_MRGPistol", "DynElect"},
            {"Gun_MRGRifle", "DynElect"},
            {"Gun_OCPDPistol", "DynElect"},
            {"Gun_OCPDRifle", "DynElect"},
            {"Gun_OCRocket", "DynElect"},
            {"Weapon_GrenadeLauncher_ME", "GasOperation"},
            // Medieval Times
            {"MedTimes_Berserker", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Warbourne", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_CapedGreen", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_CapedOrange", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_PlateJack_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Hauberk_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Brigandine_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Warbourne_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_EncasedSteel_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_Death_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_CapedBlue_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_CapedGreen_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_RoyalPlated_CapedOrange_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Acc_WargodCrest_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_BodyArmour_GodKingBlue_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_BodyArmour_GodKingGreen_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_BodyArmour_Warlord_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_BodyArmour_Combat_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Warbourne", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Plated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Scaled_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Boots_FullPlated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Warbourne_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_EncasedSteel_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_RoyalPlated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Godking_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Warlord_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"IG_RES_T2MedTimes_Boots_Combat_LegBoltGun", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Boots_Techno_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gauntlets_Warbourne", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gloves_Plated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gloves_Scaled_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Gauntlets_Plated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gauntlets_Warbourne_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Bracer_Archer_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Gauntlets_EncasedSteel_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gauntlets_RoyalPlated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Bracer_Marksman_Leg", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Gauntlets_Godking_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gauntlets_Warlord_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gloves_Combat_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Gauntlets_Techno_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Warbourne", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Helm_Headwrap_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Helm_Domed_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Helm_Sallet_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Helm_Nasal_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_FullPlated_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Warbourne_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Bascinet_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_ConicalBascinet_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_RoyalMask_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_DeathMask_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_GodKingBlue_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_GodKingGreen_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Warlord_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Torvald_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Helm_Combat_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_Gisarme_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_ShortSword_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_MaceHand_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_HammerBandit_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_WarKnife_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_DaggerKnight_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_SwordArming_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_MaceFlanged_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_MorningStar_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Melee_SwordLong_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_WarKnifeHiQ_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_Halberd_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_BattleAxe_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_AxeBearded_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_Claymore_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_WarHammer_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_KnifeBlackheart_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_SwordTechno_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_FunBunny_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_SwordVicious_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_SwordWargod_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_SwordCaladbog_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_SwordAnsweller_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_ClubTalentBreaker_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_HammerFragment_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_AxeBlood_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_AxeVidar_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Melee_HammerVoid_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_Composite", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_Composite_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_Longbow_Nan", "MedTimes_MedievalTechnologies"},
            {"MedTimes_Ranged_Crossbow_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_HandCrossbow_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_Arbalest_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_Musket_Nan", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_BlackBow_Leg", "MedTimes_AdvancedMedievalSmithing"},
            {"MedTimes_Ranged_ChargeMG_Leg", "MedTimes_AdvancedMedievalSmithing"},
            // New Ratkin Plus
            {"RK_BattleSuit", "HighClassClothing"},
            {"RK_Mask", "HighClassClothing"},
            {"RK_HeadBand", "RatkinClothing"},
            {"RK_SantaRobe", "RatkinClothing"},
            {"RK_SantaHat", "RatkinClothing"},
            {"RK_SantaSack", "RatkinClothing"},
            {"RK_WhiteCoat", "WRBoRatkinClothingltGun"},
            {"RK_BFR", "PulseTech"},
            // Polaris
            {"Apparel_PolarisShieldBelt_II", "PolarisShield"},
            {"Apparel_PolarisShieldBelt_IV", "PolarisShield"},
            {"Polarisbloc_CygnusStandardArmor", "PolarisSecretArchives"},
            {"Polarisbloc_CygnusStandardArmorC", "PolarisSecretArchives"},
            {"Polarisbloc_CygnusStandardTights", "PolarisSecretArchives"},
            {"Polarisbloc_AlkaidStrategyAssistant", "PolarisSecretArchives"},
            {"Polarisbloc_ThubanTacticalGoggles", "PolarisSecretArchives"},
            {"Polarisbloc_BodyFixTrigger", "PolarisSecretArchives"},
            {"Polarisbloc_CaniculaRifle", "PolarisSecretArchives"},
            {"Polarisbloc_CaniculaSniper", "PolarisSecretArchives"},
            {"Vanya_HunterOnSkin", "PolarisSecretArchives"},
            {"Vanya_HunterArmor", "PolarisSecretArchives"},
            {"Vanya_ChaserShieldBelt", "PolarisSecretArchives"},
            {"Vanya_Grenade", "PolarisSecretArchives"},
            {"Vanya_PlasmaSword", "PolarisSecretArchives"},
            {"Vanya_VibrateKnife", "PolarisSecretArchives"},
            {"Vanya_KineticLancer", "PolarisSecretArchives"},
            {"Vanya_SplitRifle", "PolarisSecretArchives"},
            {"Vanya_CTMinigun", "PolarisSecretArchives"},
            {"Vanya_BundlingBlaster", "PolarisSecretArchives"},
            {"Vanya_DestoryerShocker", "PolarisSecretArchives"},
            {"Vanya_RailGun", "PolarisSecretArchives"},
            {"Vanya_CompRocketLauncher", "PolarisSecretArchives"},
            {"Vanya_StalkerRifle", "PolarisSecretArchives"},
            {"Vanya_HunterSniper", "PolarisSecretArchives"},
            {"Vanya_HellSong", "PolarisSecretArchives"},
            {"PTAdvancedPsychicFoil", "PTAdvancedPsychicEquipment"},
            // Rimsenal
            {"AD_Repose", "CrucibleTech"},
            {"ADOriginal_Verdict", "CrucibleTech"},
            {"AD_Sentinel", "PlasmaTech"},
            {"AD_PBomb", "PlasmaTech"},
            {"AD_EMB", "CrucibleTech"},
            {"AD_AuxPistol", "CrucibleTech"},
            {"Gun_MCrucibleRifle", "CrucibleTech"},
            {"AD_PlasmaBombard", "PlasmaTech"},
            {"AD_CrucibleCannon", "CrucibleTech"},
            {"Gun_Harvester", "CrucibleTech"},
            {"Gun_PB", "PlasmaTech"},
            {"Gun_Thumper", "GasOperation"},
            {"Gun_RatStick", "Gunsmithing"},
            {"Feral_ScatterCannon", "Gunsmithing"},
            {"Feral_RivetCannon", "Gunsmithing"},
            {"Feral_DMG", "Gunsmithing"},
            {"Sunderer", "Gunsmithing"},
            {"Carver", "Gunsmithing"},
            {"GD_TacticalPistol", "Gunsmithing"},
            {"GD_HVSMG", "Gunsmithing"},
            {"YP_BaegYa", "SiegeTech"},
            {"JI_Dunder", "SiegeTech"},
            {"GD_Bobcat", "SiegeTech"},
            {"TE_Grief", "SiegeTech"},
            // VFE: Medieval
            {"VFEM_MeleeWeapon_Claymore", "Smithing"},
            // Naga
            {"Gun_NagaRevolver", "Gunsmithing"},
            {"Gun_NagaSMG", "GasOperation"},
            {"Gun_NagaShotgun", "Gunsmithing"},
            {"Gun_NagaRifle", "Gunsmithing"},
            {"Gun_NagaSniper", "PrecisionRifling"},
            {"Apparel_NagaShieldBelt", "ShieldBelt"},
            {"Apparel_NagaShieldEmitter", "ShieldBelt"},
            // Weapontech
            {"Gun_GatlingGun", "GasOperation"},
            {"Gun_LargeRevolver", "GasOperation"},
            {"Gun_BoltActionPistol", "GasOperation"},
            {"Gun_ServicePistol", "PrecisionRifling"},
            {"Gun_UrbanPistol", "PrecisionRifling"},
            {"Gun_VintageMachinePistol", "PrecisionRifling"},
            {"Gun_VintageSubmachineGun", "PrecisionRifling"},
            {"Gun_BullpupPDW", "PrecisionRifling"},
            {"Gun_PolymerSubmachineGun", "PrecisionRifling"},
            {"Gun_SawnOffShotgun", "GasOperation"},
            {"Gun_LeverActionShotgun", "GasOperation"},
            {"Gun_SemiAutomaticShotgun", "PrecisionRifling"},
            {"Gun_RiotShotgun", "PrecisionRifling"},
            {"Gun_RuggedCarbine", "GasOperation"},
            {"Gun_CompactCarbine", "SmithGasOperationing"},
            {"Gun_ServiceCarbine", "GasOperation"},
            {"Gun_CombatPDW", "PrecisionRifling"},
            {"Gun_WeightedBullpupCarbine", "PrecisionRifling"},
            {"Gun_ImprovisedRifle", "BlowbackOperation"},
            {"Gun_LargeLeverActionRifle", "GasOperation"},
            {"Gun_ConvertedBoltActionRifle", "GasOperation"},
            {"Gun_SportingRifle", "GasOperation"},
            {"Gun_VintageAssaultRifle", "PrecisionRifling"},
            {"Gun_RuggedAssaultRifle", "PrecisionRifling"},
            {"Gun_ModernisedRuggedAssaultRifle", "PrecisionRifling"},
            {"Gun_ServiceRifle", "GasOperation"},
            {"Gun_BalancedBullpupRifle", "PrecisionRifling"},
            {"Gun_ModernisedBullpupRifle", "PrecisionRifling"},
            {"Gun_LightCombatRifle", "PrecisionRifling"},
            {"Gun_PolymerBullpupRifle", "PrecisionRifling"},
            {"Gun_WeightedBullpupRifle", "PrecisionRifling"},
            {"Gun_PrototypeRifle", "PrecisionRifling"},
            {"Gun_CheckpointRifle", "PrecisionRifling"},
            {"Gun_DefenceRifle", "PrecisionRifling"},
            {"Gun_AutomaticBattleRifle", "PrecisionRifling"},
            {"Gun_HeavyCombatRifle", "PrecisionRifling"},
            {"Gun_RuggedLMG", "PrecisionRifling"},
            {"Gun_CompactLightMachineGun", "PrecisionRifling"},
            {"Gun_PolymerLightSupportWeapon", "PrecisionRifling"},
            {"Gun_InfantryAutomaticRifle", "PrecisionRifling"},
            {"Gun_WeightedLightSupportWeapon", "PrecisionRifling"},
            {"Gun_VintageLightMachineGun", "PrecisionRifling"},
            {"Gun_VintageGPMG", "PrecisionRifling"},
            {"Gun_GPMG", "PrecisionRifling"},
            {"Gun_BreechLoadingSniper", "Optics"},
            {"Gun_LeverActionSniper", "Optics"},
            {"Gun_ReconRifle", "Optics"},
            {"Gun_RuggedMarksmansRifle", "Optics"},
            {"Gun_VintageSniper", "Optics"},
            {"Gun_SpecialPurposeRifle", "Optics"},
            {"Gun_SniperSupportRifle", "Optics"},
            {"Gun_AntiMaterielRifle", "Optics"},
            {"Gun_ModernisedArquebus", "BlowbackOperation"},
            {"Gun_AkimboMachinePistols", "PrecisionRifling"},
            {"Gun_PersonalisedBullpupPDW", "PrecisionRifling"},
            {"Gun_AkimboLeverActionShotguns", "GasOperation"},
            {"Gun_VintageLeverActionRifle", "GasOperation"},
            {"Gun_GoldPlatedRuggedAssaultRifle", "PrecisionRifling"},
            {"Gun_ModifiedLightSupportWeapon", "PrecisionRifling"},
            {"Gun_AutomaticSniperRifle", "Optics"},
            {"Gun_QuadLauncher", "GrenadeLaunchers"},
            {"Gun_SpecialOperationsRifle", "Optics"},
            {"Gun_MachinePistol", "PrecisionRifling"},
            {"Gun_HeavySMG", "PrecisionRifling"},
            // Rimmunation
            {"RNGun_HK417HRTDMR", "PrecisionRifling"},
            {"RNGun_Remington870HRT", "Gunsmithing"},
            {"RNGun_G3SGDMR", "PrecisionRifling"},
            {"RNGun_HK417DMR", "PrecisionRifling"},
            {"RNGun_WA2000DMR", "PrecisionRifling"},
            {"RNGun_L129A1DMR", "PrecisionRifling"},
            {"RNGun_QBU88DMR", "PrecisionRifling"},
            {"RNGun_AR10DMR", "PrecisionRifling"},
            {"RNGun_M14EBR", "PrecisionRifling"},
            {"RNGun_M14EBRMilSpec", "PrecisionRifling"},
            {"RNGun_M39EMR", "PrecisionRifling"},
            {"RNGun_M39EMRMilSpec", "PrecisionRifling"},
            {"RNGun_Mk14EBR", "PrecisionRifling"},
            {"RNGun_M110SASSDMR", "PrecisionRifling"},
            {"RNGun_M21DMR", "PrecisionRifling"},
            {"RNGun_M110SASSSDDMR", "PrecisionRifling"},
            {"RNGun_RFBDMR", "GasOperation"},
            {"RNGun_SCARMk20DMR", "PrecisionRifling"},
            {"RNGun_MK11DMR", "PrecisionRifling"},
            {"RNGun_DragunovDMR", "PrecisionRifling"},
            {"RNGun_ZastavaM76DMR", "PrecisionRifling"},
            {"RNGun_SVKDMR", "PrecisionRifling"},
            {"RNGun_SVUDMR", "PrecisionRifling"},
            {"RNGun_SVUADMR", "PrecisionRifling"},
            {"RNGun_NagantRevolver", "Gunsmithing"},
            {"RNGun_RagingBull", "Gunsmithing"},
            {"RNGun_Remington1858P", "Gunsmithing"},
            {"RNGun_ColtPeacemaker", "Gunsmithing"},
            {"RNGun_ColtPeacemaker_II", "Gunsmithing"},
            {"RNGun_ColtCobra", "Gunsmithing"},
            {"RNGun_Mateba", "Gunsmithing"},
            {"RNGun_SWModel29P", "Gunsmithing"},
            {"RNGun_ASVAL", "PrecisionRifling"},
            {"RNGun_KS23S", "Gunsmithing"},
            {"RNGun_KSGS", "GasOperation"},
            {"RNGun_Model1887LA", "Gunsmithing"},
            {"RNGun_Mossberg500TacticalS", "Gunsmithing"},
            {"RNGun_Remington870S", "Gunsmithing"},
            {"RNGun_Remington870TacticalS", "Gunsmithing"},
            {"RNGun_SuperShorty", "Gunsmithing"},
            {"RNGun_Supernova", "Gunsmithing"},
            {"RNGun_UTS15S", "Gunsmithing"},
            {"RNGun_M1014S", "Gunsmithing"},
            {"RNSci_Railgun", "ChargedShot"},
            {"RNAir_RedSpectre", "MicroelectronicsBasics"},
            {"RNAir_SerbAirstrike", "MicroelectronicsBasics"},

        };

        public static bool GetHardAssignment(ThingDef thing, out ResearchProjectDef rpd)
        {
            string name;
            if (hardAssignment.TryGetValue(thing.defName, out name))
            {
                rpd = DefDatabase<ResearchProjectDef>.GetNamedSilentFail(name);
                if (rpd != null)
                    return true;
            }
            rpd = null;
            return false;
        }

        public static bool GetOverrideAssignment(ThingDef thing, out ResearchProjectDef rpd)
        {
            string name;
            if (overrideAssignment.TryGetValue(thing.defName, out name))
            {
                rpd = DefDatabase<ResearchProjectDef>.GetNamedSilentFail(name);
                if (rpd != null)
                    return true;
            }
            rpd = null;
            return false;
        }

        public static bool ProjectIsExempt(ResearchProjectDef rpd)
        {
            return ArcaneTechnologySettings.exemptClothing && exemptProjects.Contains(rpd.defName);
        }

    }
}
